on:
  pull_request:
    types: [ labeled ]
      
name: AzureResourceDeploy-plan

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID  }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

jobs:
  build:
    name: 'terraform (${{ github.event.label.name }}-plan)'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1   
        
      - name: Terraform Init        
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '${{ github.event.label.name }}'
          tf_actions_comment: true      

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '${{ github.event.label.name }}'
          tf_actions_comment: true
