on:
  push:
    branches:
      - main
      
name: AzureResourceDeploy-apply

jobs:
  AzureResourceDeploy-apply:
    name: 'terraform (${{ github.event.commits[0].message }}-apply)'
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1   
        
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '${{ github.event.commits[0].message }}'
          tf_actions_comment: true      

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '${{ github.event.commits[0].message }}'
          tf_actions_comment: true
        
      - name: Terraform apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.5
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: '${{ github.event.commits[0].message }}'
          tf_actions_comment: true
